AWSTemplateFormatVersion: "2010-09-09"

Resources:
    API:
        Type: "AWS::ApiGatewayV2::Api"
        Properties:
            Name: test
            ProtocolType: HTTP

    Route:
        Type: "AWS::ApiGatewayV2::Route"
        Properties:
            ApiId: !Ref API
            AuthorizationType: "NONE"
            RouteKey: $default
            Target: !Sub "integrations/${Integration}"

    Authorizer:
        Type: "AWS::ApiGatewayV2::Authorizer"
        Properties:
            ApiId: !Ref API
            AuthorizerType: JWT
            IdentitySource: 
                - "$request.header.Authorization"
            Name: JWTAuthorizer
            JwtConfiguration:
                Audience: #FIXME
                    #- urn:amazon:cognito:sp:eu-central-1_Z2jjKN2eh
                    - 7i8d9tc0ooeb9qsbupmq75s235
                Issuer: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_Z2jjKN2eh

    Integration:
        Type: "AWS::ApiGatewayV2::Integration"
        Properties:
            ApiId: !Ref API
            ConnectionType: "INTERNET" #FIXME VPC_LINK
            IntegrationMethod: ANY
            IntegrationType: HTTP_PROXY
            #IntegrationUri: http://tschenett.ch
            IntegrationUri: https://s3-s3bucketforwebsitecontent-1kllk7g007r2l.s3.eu-central-1.amazonaws.com
            PayloadFormatVersion: "1.0"
            #TlsConfig

    Route2:
        Type: "AWS::ApiGatewayV2::Route"
        Properties:
            ApiId: !Ref API
            AuthorizationType: "JWT"
            AuthorizerId: !Ref Authorizer
            #AuthorizationScopes:
            #    - openid
            RouteKey: ANY /furthermore/{proxy+}
            Target: !Sub "integrations/${Integration2}"

    Integration2:
        Type: "AWS::ApiGatewayV2::Integration"
        Properties:
            ApiId: !Ref API
            ConnectionType: "INTERNET" #FIXME VPC_LINK
            IntegrationMethod: ANY
            IntegrationType: HTTP_PROXY
            IntegrationUri: http://furthermore.ch/{proxy}
            PayloadFormatVersion: "1.0"
            #TlsConfig

    Stage:
        Type: "AWS::ApiGatewayV2::Stage"
        Properties: 
            ApiId: !Ref API
            AutoDeploy: true
            #DeploymentId: !Ref Deployment
            StageName: $default

    #Deployment:
    #    Type: "AWS::ApiGatewayV2::Deployment"
    #    Properties:
    #        ApiId: !Ref API
    #        StageName 

Outputs:
    API:
        Value: !Ref API
